//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IAttractionDatabase.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//
package project.android.com.android5777_9254_6826.model.datasource;


import android.content.ContentValues;
import android.database.Cursor;
import android.net.Uri;

import java.util.ArrayList;
import java.util.Date;

import project.android.com.android5777_9254_6826.model.entities.Account;
import project.android.com.android5777_9254_6826.model.entities.Attraction;
import project.android.com.android5777_9254_6826.model.entities.Properties;

public interface IAttractionDatabase extends IDatabase {
    /**
     * @param Type
     * @param Country
     * @param StartDate
     * @param EndDate
     * @param Price
     * @param Description
     * @param BusinessID
     * @return returns true if succeeded , else false;
     */
    int addNewAttraction(Properties.AttractionType Type,String AttractionName, String Country, String StartDate,
                         String EndDate, float Price, String Description, String BusinessID);
    int addNewAttraction(Attraction toInsert);

    /**
     * @return list of the attraction in the database
     */
    ArrayList<Attraction> getAttractionList();

    /**
     * gets tha attractionlist
     * @param BusinessID
     * @return  ArrayList<Attraction>
     */
    ArrayList<Attraction> getAttractionList(String BusinessID);

    /**
     *
     * @return Attraction in Cursor format
     * @throws Exception
     */
    Cursor getAttractionCursor() throws Exception;

    /**
     *  get Attraction by id
     * @param attractionID
     * @return Attraction
     * @throws Exception
     */
    Attraction getAttraction(String attractionID) throws Exception;
    /**
     *  get Attraction by business id and the attname
     * @param BusinessID, AttrationName
     * @return Attraction
     * @throws Exception
     */
    Attraction getAttraction(String BusinessID,String AttrationName) throws Exception;

    /**
     * checks if lately an attraction was added to database
     * @return boolean
     */
    boolean ifNewAttractionAdded();

    int removeAttraction(String attractionID);

    /**
     * deletes Attraction by id
     * @param rowID
     * @return
     */
    int removeAttraction(int rowID);
    Uri insert(Attraction ac);
    int delete(Uri uri, String selection, String[] selectionArgs);
    int update(Uri uri, ContentValues values, String selection,
               String[] selectionArgs);
    Cursor query(Uri uri, String[] projection, String selection,
                 String[] selectionArgs, String sortOrder);
}
