//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Business.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//

package project.android.com.android5777_9254_6826.model.entities;


import android.os.Parcel;
import android.os.Parcelable;
import android.util.Log;

import java.io.Serializable;
import java.net.MalformedURLException;
import java.net.URL;

public class Business implements Serializable {


    private String AccountID;
    private String BusinessID;
    private String BusinessName;
    private Address BusinessAddress;
    private String Email;
    private String Website;

    public static final String BUSINESS = "Business";
    public static final String ACCOUNTID = Account.ID;
    public static final String ID = "BusinessID";
    public static final String NAME = "BusinessName";
    public static final String ADDRESS = "baddr";
    public static final String EMAIL = "Email";
    public static final String WEBSITE = "Website";

    /**
     * Returns an array with the names of the attributes
     * @return an array with the attributes names.
     */
    public static String[] getColumns(){
        return new String[]{ACCOUNTID,ID,NAME,Address.COUNTRY,Address.CITY,Address.STREET,EMAIL,WEBSITE};
    }

    //region getters and setters
    public String getAccountID() {
        return AccountID;
    }

    public void setAccountID(String accountID) {
        AccountID = accountID;
    }

    public String getBusinessID() {
        return BusinessID;
    }

    public void setBusinessID(String businessID) {
        BusinessID = businessID;
    }

    public String getBusinessName() {
        return BusinessName;
    }

    public void setBusinessName(String businessName) {
        BusinessName = businessName;
    }

    public Address getBusinessAddress() {
        return BusinessAddress;
    }

    public void setBusinessAddress(Address businessAddress) {
        BusinessAddress = businessAddress;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String email) {
        Email = email;
    }

    public String getWebsite() {
        return Website;
    }

    public void setWebsite(String  website) {
        Website = website;
    }
    //endregion

    /**
     * Returns an array with the names of the attributes
     * @return an array with the attributes names.
     */
    public Object[] getAttributes(){
        return new Object[] {
                AccountID,
                BusinessID,
                BusinessName,
                BusinessAddress.getCountry(),
                BusinessAddress.getCity(),
                BusinessAddress.getStreet(),
                Email,
                Website
        };
    }
    /**
     * Returns the value of an attribute
     * @param Col the attribute to get the value for
     * @return The value for that attribute
     * @throws Exception if a wrong attribute name was entered
     */
    public String getValue(String Col) throws Exception {
        switch (Col){
            case Business.ACCOUNTID:
                return getAccountID();
            case Address.COUNTRY:
                return getBusinessAddress().getCountry();
            case Address.CITY:
                return getBusinessAddress().getCity();
            case Address.STREET:
                return getBusinessAddress().getStreet();
            case Business.ID:
                return getBusinessID();
            case Business.EMAIL:
                return getEmail();
            case Business.NAME:
                return getBusinessName();
            case Business.WEBSITE:
                return getWebsite();
            default:
                throw new Exception("Column doesn't Exist");
        }
    }
    /**
     * Constructor
     * @param accountID
     * @param id
     * @param name
     * @param address
     * @param email
     * @param website
     */
    public Business(String accountID,String id, String name, Address address, String email, String website) {
        AccountID = accountID;
        BusinessID = id;
        BusinessName = name;
        BusinessAddress = address;
        Email = email;
        Website = website;
    }
}
