//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Business.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//

package project.android.com.android5777_9254_6826.model.entities;


import android.os.Parcel;
import android.os.Parcelable;
import android.util.Log;

import java.io.Serializable;
import java.net.MalformedURLException;
import java.net.URL;

public class Business implements Serializable {


    private String AccountID;
    private String BusinessID;
    private String BusinessName;
    private Address BusinessAddress;
    private String Email;
    private String Website;

    public static final String BUSINESS = "Business";
    public static final String ACCOUNTID = Account.ID;
    public static final String ID = "BusinessID";
    public static final String NAME = "BusinessName";
    public static final String ADDRESS = "baddr";
    public static final String EMAIL = "Email";
    public static final String WEBSITE = "Website";

    public String getAccountID() {
        return AccountID;
    }

    public void setAccountID(String accountID) {
        AccountID = accountID;
    }

    public String getBusinessID() {
        return BusinessID;
    }

    public void setBusinessID(String businessID) {
        BusinessID = businessID;
    }

    public String getBusinessName() {
        return BusinessName;
    }

    public void setBusinessName(String businessName) {
        BusinessName = businessName;
    }

    public Address getBusinessAddress() {
        return BusinessAddress;
    }

    public void setBusinessAddress(Address businessAddress) {
        BusinessAddress = businessAddress;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String email) {
        Email = email;
    }

    public String getWebsite() {
        return Website;
    }

    public void setWebsite(String  website) {
        Website = website;
    }

    public Business(String accountID,String id, String name, Address address, String email, String website) {
        AccountID = accountID;
        BusinessID = id;
        BusinessName = name;
        BusinessAddress = address;
        Email = email;
        Website = website;
    }
}
