//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Account.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//
package project.android.com.second_app.model.entities;


import java.io.Serializable;

public class Account implements Serializable{

	private String UserName;
	private String Password;
	private long AccountNumber;

	public static final String ACCOUNT = "Account";
	public static final String USERNAME = "UserName";
	public static final String PASSWORD = "Password";
	public static final String ID = "AccountNumber";

	public static String[] getColumns(){
		String[] col = new String[]{USERNAME,PASSWORD,ID};
		return col;
	}

	public Account(long id, String userName, String password) {
		this.AccountNumber = id;
		this.UserName = userName;
		this.Password = password;
	}

	public Object[] getAttributes(){
		return new Object[] {UserName,Password,AccountNumber};
	}

	public String getValue(String Col) throws Exception {
		switch (Col){
			case Account.USERNAME:
				return getUserName();
			case Account.PASSWORD:
				return getPassword();
			case Account.ID:
				return String.valueOf(getAccountNumber());
			default:
				throw new Exception("Column doesn't Exist");
		}
	}

	//region getters and setters
	public long getAccountNumber() {
		return AccountNumber;
	}

	public void setAccountNumber(long accountNumber) {
		AccountNumber = accountNumber;
	}

	public String getUserName() {
		return UserName;
	}

	public void setUserName(String userName) {
		UserName = userName;
	}

	public String getPassword() {
		return Password;
	}

	public void setPassword(String password) {
		Password = password;
	}

	//endregion


}
