//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Attraction.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//
package project.android.com.second_app.model.entities;
import java.io.Serializable;



public class Attraction implements Serializable {
	private Properties.AttractionType Type;
	private String Country;
	private String StartDate;
	private String EndDate;
	private float Price;
	private String Description;
	private String BusinessID;
	private String AttractionID;
	private String AttractionName;

	public static final String ATTRACTION = "Attraction";
	public static final String TYPE = "Type";
	public static final String COUNTRY = "Country";
	public static final String STARTDATE = "StartDate";
	public static final String ENDDATE = "EndDate";
	public static final String PRICE = "Price";
	public static final String DESCRIPITION = "Description";
	public static final String BUSINESSID = Business.ID;
	public static final String ID = "AttractionID";
	public static final String NAME = "AttractionName";

	public static String[] getColumns(){
		return new String[]{TYPE,COUNTRY,STARTDATE,ENDDATE,PRICE,DESCRIPITION,BUSINESSID,ID,NAME};
	}

	public Attraction(String attractionID,Properties.AttractionType type,String attractionName,  String country, String startDate, String endDate, float price, String description, String businessID) {
		AttractionName= attractionName;
		Type = type;
		Country = country;
		StartDate = startDate;
		EndDate = endDate;
		Price = price;
		Description = description;
		BusinessID = businessID;
		AttractionID = attractionID;
	}

	public Object[] getAttributes(){
		return new Object[] {Type,Country,StartDate,EndDate,Price,Description,BusinessID,AttractionID,AttractionName};
	}

	public String getValue(String Col) throws Exception {
		switch (Col){
			case Attraction.BUSINESSID:
				return getBusinessID();
			case Attraction.TYPE:
				return getType().toString();
			case Attraction.COUNTRY:
				return getCountry();
			case Attraction.STARTDATE:
				return getStartDate();
			case Attraction.ENDDATE:
				return getEndDate();
			case Attraction.PRICE:
				return String.valueOf(getPrice());
			case Attraction.DESCRIPITION:
				return getDescription();
			case Attraction.ID:
				return getAttractionID();
			case Attraction.NAME:
				return getAttractionName();
			default:
				throw new Exception("Column doesn't Exist");
		}
	}
	//region getters and setters
	public String getAttractionName() {
		return AttractionName;
	}

	public void setAttractionName(String attractionName) {
		AttractionName = attractionName;
	}
	public Properties.AttractionType getType() {
		return Type;
	}

	public void setType(Properties.AttractionType type) {
		Type = type;
	}

	public String getCountry() {
		return Country;
	}

	public void setCountry(String country) {
		Country = country;
	}

	public String getStartDate() {
		return StartDate;
	}

	public void setStartDate(String startDate) {
		StartDate = startDate;
	}

	public String getEndDate() {
		return EndDate;
	}

	public void setEndDate(String endDate) {
		EndDate = endDate;
	}

	public float getPrice() {
		return Price;
	}

	public void setPrice(float price) {
		Price = price;
	}

	public String getDescription() {
		return Description;
	}

	public void setDescription(String description) {
		Description = description;
	}

	public String getBusinessID() {
		return BusinessID;
	}

	public void setBusinessID(String businessID) {
		BusinessID = businessID;
	}

	public String getAttractionID() {
		return AttractionID;
	}

	public void setAttractionID(String attractionID) {
		AttractionID = attractionID;
	}
	//endregion
}
